### ISSUE TITLE
[iOS] 이미지 업로드 허용크기가 몇인가요?

### ISSUE THREAD

**Issue by FirstDo** [Sal-Mal/salmal-be#107]
저번에 5mb로 들었던것 같은데 실제로는 훨씬 적은것 같아서요..!!
1mb만 넘어도 현재 안되는것 같습니다

알려주시면 거기에 맞추도록 하겠습니다

**Comment by seu0313** [comment]
@pia2011 이미지 허용 최대 크기 알려주세요 :)
